//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominos.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ITEMS
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> ProductDiscountPrice { get; set; }
        public Nullable<double> DiscountValue { get; set; }
    }
}
