//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominos.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
    }
}
